// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrtTnsgJ-R31JVP7IAiVQrWf0a9HTNlzk',
    appId: '1:715400827137:web:241a499489ded117918b00',
    messagingSenderId: '715400827137',
    projectId: 'lbpalert',
    authDomain: 'lbpalert.firebaseapp.com',
    storageBucket: 'lbpalert.appspot.com',
    measurementId: 'G-Q2993V6RJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcKiYrXYgdyL1Z9w1ZDtx3C0HEvtzLIqI',
    appId: '1:715400827137:android:5169bf997d566e94918b00',
    messagingSenderId: '715400827137',
    projectId: 'lbpalert',
    storageBucket: 'lbpalert.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpBYfVMvYPxbZUb5iTLCrnnND0l2d-yu8',
    appId: '1:715400827137:ios:f7a8ae7c7fcaef18918b00',
    messagingSenderId: '715400827137',
    projectId: 'lbpalert',
    storageBucket: 'lbpalert.appspot.com',
    iosClientId: '715400827137-nbovnvp692gq1j425t0qsfhlhtqsgthf.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );
}
